# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

      
#       - name: Build Docker Image
#         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/payguardserver:latest .

      
#       - name: Push Docker Image
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/payguardserver:latest  

#       - name: Verify Pushed Image
#         run: docker pull ${{ secrets.DOCKER_USERNAME }}/payguardserver:latest

#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST}}
#           username: ${{ secrets.SSH_USERNAME}}
#           key: ${{ secrets.SSH_KEY}}
#           script: |
#             sudo docker pull ${{ secrets.DOCKER_USERNAME }}/payguardserver:latest
#             sudo docker stop payguardserver || true
#             sudo docker rm payguardserver || true
#             sudo docker run -d --name payguardserver -p 8000:8000 --env DATABASE_URL=${{ secrets.DB_URL }} --env PORT=8000 --env JWT_SECRET=${{ secrets.JWT_SECRET }} ${{ secrets.DOCKER_USERNAME }}/payguardserver:latest  

name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v4

      # Step 2: Create the private key file from the secret
      - name: Create private key file
        run: echo "${{ secrets.PRIVATE_KEY }}" > nodejs-server.pem

      # Step 3: Set permissions for the private key
      - name: Set permissions for private key
        run: chmod 400 nodejs-server.pem

      # Step 4: Log in to EC2 instance and check connectivity
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i nodejs-server.pem ubuntu@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            echo "Login successful!"
            uname -a  # Check system details
            # Add any additional commands here
EOF
