name: Deploy server to EC2 using dockerhub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Create private key file
        run: echo "${{ secrets.PRIVATE_KEY }}" > ec2-key.pem

      - name: Set permissions for private key
        run: chmod 400 ec2-key.pem
        
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            echo "Login successful!"
            uname -a
            
            # Log in to Docker (if not already logged in)
            echo "Logging in to Docker Hub..."
            echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

            # Clean up all existing containers
            echo "Cleaning up old containers..."
            sudo docker stop $(sudo docker ps -aq) || true
            sudo docker rm $(sudo docker ps -aq) || true
            
            # Clean up all unused images
            echo "Cleaning up old images..."
            sudo docker rmi $(sudo docker images -q) || true
            
            # Clean up unused volumes (optional but useful)
            echo "Cleaning up unused volumes..."
            sudo docker volume prune -f
            
            # Pull the latest image from Docker Hub
            echo "Pulling latest image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/payguardserver:latest
            
            # Run the new image
            echo "Running the new container..."
            sudo docker run -d --name payguardserver -p 8000:8000 \
              --env DATABASE_URL=${{ secrets.DB_URL }} --env PORT=8000 --env JWT_SECRET=${{ secrets.JWT_SECRET }} ${{ secrets.DOCKER_USERNAME }}/payguardserver:latest
          EOF

      - name: Cleanup private key
        run: rm -f ec2-key.pem

      - name: Successful message
        run: echo "Deployment was successful"
