name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v4

      # Step 2: Create the private key file from the secret
      - name: Create private key file
        run: echo "${{ secrets.PRIVATE_KEY }}" > nodejs-server.pem

      # Step 3: Set permissions for the private key
      - name: Set permissions for private key
        run: chmod 400 nodejs-server.pem

      # Step 4: Log in to EC2 instance and check connectivity
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i nodejs-server.pem ubuntu@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            echo "Login successful!"
            uname -a  # Check system details
